//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendaVirtual
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int id { get; set; }
        public string usuario { get; set; }
        public Nullable<int> producto_id { get; set; }
        public Nullable<double> cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
